services:
  web:
    image: php:7.4-apache
    ports:
      - "4500:80"
    volumes:
      - /compose-project/app/:/var/www/html
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
